name: ezops-test-Pipeline

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: 
      - self-hosted
      - linux

    steps:
    - uses: actions/checkout@v3
      
    - name: Build the Docker image
      run: sudo docker build -t ezops-test-backend .

    - name: Delete Old docker container
      run: sudo docker rm -f ezops-test-backend || true

    - name: Run Docker Container
      run: sudo docker run -d -p 3000:3000 --name ezops-test-backend ezops-test-backend